FROM node:22-alpine
RUN corepack enable && corepack prepare pnpm@latest --activate
WORKDIR /app
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install || true
COPY tsconfig*.json ./
COPY src ./src
EXPOSE 3000
CMD ["pnpm","start:dev"]
