services:
  gateway:
    build: ../gateway
    working_dir: /app
    # just install + run; do NOT rm -rf node_modules
    command: sh -lc "pnpm install && pnpm start:dev"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CI=true                 # avoid pnpm interactive prompts
      - PNPM_HOME=/root/.local/share/pnpm
    volumes:
      - ../gateway:/app
      - gateway_node_modules:/app/node_modules  # keep deps in container

  frontend:
    build: ../frontend
    working_dir: /app
    command: sh -lc "pnpm install && pnpm dev --port 3000 --hostname 0.0.0.0"
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - CI=true
      # uncomment if HMR is flaky on Windows:
      # - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../frontend:/app
      - frontend_node_modules:/app/node_modules

  redis:
    image: redis:7
    ports: ["6379:6379"]

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]

volumes:
  gateway_node_modules:
  frontend_node_modules:
